# Generated by Django 4.1 on 2024-03-24 14:56

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_image_remove_post_video_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.post_content_upload_path),
        ),
    ]
