# Generated by Django 4.1 on 2024-03-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
